"""FastAPI app exposing the Torrey Pines shaker over lab status spec v1.1.

Endpoints
---------

Spec-mandated (always available):

* ``GET /``         - probe: ``ProbeResponse``
* ``GET /health``   - liveness: ``HealthResponse``
* ``GET /status``   - full ``EquipmentStatus`` envelope (side-effect-free)
* ``GET /openapi.json`` - generated by FastAPI

Claim protocol (v1.1):

* ``POST /control/claim``     - ``ClaimRequest`` -> ``ClaimResponse``
* ``POST /control/heartbeat`` - header ``X-Claim-Token``
* ``POST /control/release``   - header ``X-Claim-Token``

Control (gated by ``X-Claim-Token`` when ``enforce_claims=True``):

* ``POST /control/startup``
* ``POST /control/shutdown``
* ``POST /control/shake/set_temperature`` - ``{temperature_c}``
* ``POST /control/shake/set_speed``       - ``{speed_level}``
* ``POST /control/shake/start``           - ``{speed_level, temperature_c,
                                              duration_s, wait_for_temperature?}``
* ``POST /control/shake/stop``
"""

from __future__ import annotations

import asyncio
import logging
from contextlib import asynccontextmanager
from typing import Annotated, Any

from fastapi import Depends, FastAPI, Header, HTTPException, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from . import config as _config
from .claims import ClaimConflict, UnknownClaim
from .models import (
    PROTOCOL_VERSION,
    ClaimRejection,
    ClaimRequest,
    ClaimResponse,
    EquipmentStatus,
    HealthResponse,
    ProbeResponse,
)
from .service import ShakerService, TemperatureNotReady

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Request/response bodies for /control/*
# ---------------------------------------------------------------------------


class SetTemperatureRequest(BaseModel):
    temperature_c: float = Field(
        ge=-20.0,
        le=110.0,
        description="Setpoint in degrees C. Driver-enforced range -20..+110.",
    )


class SetSpeedRequest(BaseModel):
    speed_level: int = Field(
        ge=1,
        le=9,
        description=(
            "Orbital speed level 1..9 (driver units; not RPM). Level 0 is "
            "motor-off; use POST /control/shake/stop to halt."
        ),
    )


class ShakeStartRequest(BaseModel):
    speed_level: int = Field(ge=1, le=9)
    temperature_c: float = Field(ge=-20.0, le=110.0)
    duration_s: float = Field(gt=0.0, description="Cycle length in seconds.")
    wait_for_temperature: bool = Field(
        default=False,
        description=(
            "When true, /control/shake/start waits for the heater to "
            "reach `temperature_c` (within configured tolerance) before "
            "starting the duration countdown."
        ),
    )


class CommandResponse(BaseModel):
    ok: bool = True
    message: str | None = None
    details: dict[str, Any] | None = None


# ---------------------------------------------------------------------------
# Internal exception for top-level JSON error bodies (claims / 412)
# ---------------------------------------------------------------------------


class _ClaimResponseException(Exception):
    def __init__(
        self,
        status_code: int,
        payload: dict[str, Any],
        headers: dict[str, str] | None = None,
    ) -> None:
        super().__init__(f"HTTP {status_code}")
        self.status_code = status_code
        self.payload = payload
        self.headers = headers or {}


# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------


def create_app(
    *,
    dry_run: bool | None = None,
    enforce_claims: bool | None = None,
) -> FastAPI:
    if dry_run is None:
        dry_run = bool(_config.get("service", "dry_run", False))
    if enforce_claims is None:
        enforce_claims = bool(_config.get("service", "enforce_claims", True))

    service = ShakerService(
        dry_run=dry_run,
        enforce_claims=enforce_claims,
    )
    startup_timeout = float(
        _config.get("service", "startup_connect_timeout_s", 10.0)
    )

    @asynccontextmanager
    async def lifespan(app: FastAPI):  # noqa: ARG001
        try:
            await asyncio.wait_for(service.startup(), timeout=startup_timeout)
            logger.info("Shaker auto-connect succeeded")
        except asyncio.TimeoutError:
            logger.warning(
                "Shaker connect timed out after %.0fs; leaving in requires_init",
                startup_timeout,
            )
        except Exception as exc:
            logger.warning("Shaker auto-connect failed: %s", exc)
        try:
            yield
        finally:
            try:
                await service.claims.force_clear()
            except Exception:
                logger.exception("Error while clearing claim on shutdown")
            await service.shutdown()

    app = FastAPI(
        title="Torrey Pines Shaker API",
        version="0.1.0",
        description=(
            "REST API for the Torrey Pines Scientific shaker (SC20 series). "
            "Conforms to the AC lab equipment status spec v1.1 - see "
            "`docs/STATUS_SPEC.md` in the ac-organic-lab monorepo."
        ),
        lifespan=lifespan,
    )

    cors_origins: Any = _config.get("service", "cors_origins", ["*"])
    app.add_middleware(
        CORSMiddleware,
        allow_origins=list(cors_origins),
        allow_credentials=False,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.exception_handler(_ClaimResponseException)
    async def _claim_response_handler(request, exc: _ClaimResponseException):  # noqa: ARG001
        return JSONResponse(
            status_code=exc.status_code,
            content=exc.payload,
            headers=exc.headers,
        )

    # ---- Spec endpoints ---------------------------------------------------

    @app.get("/", response_model=ProbeResponse, tags=["spec"])
    async def probe() -> ProbeResponse:
        return ProbeResponse(
            equipment_id=service.equipment_id,
            equipment_name=service.equipment_name,
            protocol_version=PROTOCOL_VERSION,
        )

    @app.get("/health", response_model=HealthResponse, tags=["spec"])
    async def health() -> HealthResponse:
        return HealthResponse()

    @app.get("/status", response_model=EquipmentStatus, tags=["spec"])
    async def status() -> EquipmentStatus:
        return await service.get_status()

    # ---- Claim protocol (v1.1) -------------------------------------------

    async def require_claim(
        x_claim_token: Annotated[str | None, Header(alias="X-Claim-Token")] = None,
    ) -> None:
        if not service.enforce_claims:
            return
        if x_claim_token is None or not await service.claims.validate(x_claim_token):
            current = await service.claims.current()
            payload: dict[str, Any] = {
                "detail": (
                    "missing or invalid X-Claim-Token; POST /control/claim first"
                ),
                "claimed_by": (
                    current.model_dump(mode="json") if current is not None else None
                ),
                "retry_after_s": None,
            }
            raise _ClaimResponseException(status_code=423, payload=payload)

    @app.post(
        "/control/claim",
        response_model=ClaimResponse,
        responses={409: {"model": ClaimRejection}},
        tags=["claim"],
    )
    async def control_claim(req: ClaimRequest) -> ClaimResponse:
        try:
            return await service.claims.acquire(req)
        except ClaimConflict as exc:
            rejection = ClaimRejection(
                detail=str(exc),
                claimed_by=exc.claimed_by,
                retry_after_s=exc.retry_after_s,
            )
            raise _ClaimResponseException(
                status_code=409,
                payload=rejection.model_dump(mode="json"),
                headers={"Retry-After": str(int(exc.retry_after_s + 1))},
            )

    @app.post(
        "/control/heartbeat",
        response_model=ClaimResponse,
        tags=["claim"],
    )
    async def control_heartbeat(
        x_claim_token: Annotated[str | None, Header(alias="X-Claim-Token")] = None,
    ) -> ClaimResponse:
        try:
            return await service.claims.heartbeat(x_claim_token)
        except UnknownClaim:
            raise HTTPException(
                status_code=401,
                detail="claim token is unknown or expired; POST /control/claim",
            )

    @app.post("/control/release", status_code=204, tags=["claim"])
    async def control_release(
        x_claim_token: Annotated[str | None, Header(alias="X-Claim-Token")] = None,
    ) -> Response:
        await service.claims.release(x_claim_token)
        return Response(status_code=204)

    # ---- Control endpoints -----------------------------------------------

    @app.post("/control/startup", response_model=CommandResponse, tags=["control"])
    async def control_startup(_claim: None = Depends(require_claim)) -> CommandResponse:
        try:
            await service.startup()
        except Exception as exc:
            raise HTTPException(status_code=503, detail=str(exc))
        service.clear_last_error_on_success()
        return CommandResponse(message="Connected")

    @app.post("/control/shutdown", response_model=CommandResponse, tags=["control"])
    async def control_shutdown(_claim: None = Depends(require_claim)) -> CommandResponse:
        await service.shutdown()
        service.clear_last_error_on_success()
        return CommandResponse(message="Disconnected")

    @app.post(
        "/control/shake/set_temperature",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_set_temperature(
        req: SetTemperatureRequest,
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        try:
            await service.set_temperature(req.temperature_c)
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except ValueError as exc:
            raise HTTPException(status_code=422, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        service.clear_last_error_on_success()
        return CommandResponse(message=f"Set temperature to {req.temperature_c} C")

    @app.post(
        "/control/shake/set_speed",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_set_speed(
        req: SetSpeedRequest,
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        try:
            await service.set_speed(req.speed_level)
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except ValueError as exc:
            raise HTTPException(status_code=422, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        service.clear_last_error_on_success()
        return CommandResponse(message=f"Set speed level to {req.speed_level}")

    @app.post(
        "/control/shake/start",
        response_model=CommandResponse,
        responses={
            412: {
                "description": (
                    "Precondition refusal. Body shape: "
                    "{detail, actual_c, setpoint_c, tolerance_c, retry_after_s}. "
                    "Returned when wait_for_temperature=True and the setpoint "
                    "was not reached within the configured timeout."
                )
            }
        },
        tags=["control"],
    )
    async def control_shake_start(
        req: ShakeStartRequest,
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        try:
            info = await service.start_shake(
                speed_level=req.speed_level,
                temperature_c=req.temperature_c,
                duration_s=req.duration_s,
                wait_for_temperature=req.wait_for_temperature,
            )
        except TemperatureNotReady as exc:
            payload: dict[str, Any] = {
                "detail": str(exc),
                "actual_c": exc.actual_c,
                "setpoint_c": exc.setpoint_c,
                "tolerance_c": exc.tolerance_c,
                "retry_after_s": exc.retry_after_s,
            }
            headers: dict[str, str] = {}
            if exc.retry_after_s is not None:
                headers["Retry-After"] = str(int(exc.retry_after_s))
            raise _ClaimResponseException(
                status_code=412, payload=payload, headers=headers
            )
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except ValueError as exc:
            raise HTTPException(status_code=422, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        service.clear_last_error_on_success()
        # Serialise datetimes via Pydantic-friendly isoformat.
        details = {
            "started_at": info["started_at"].isoformat(),
            "ends_at": info["ends_at"].isoformat(),
            "duration_s": info["duration_s"],
            "speed_level": info["speed_level"],
            "temperature_c": info["temperature_c"],
        }
        return CommandResponse(message="Shake cycle started", details=details)

    @app.post("/control/shake/stop", response_model=CommandResponse, tags=["control"])
    async def control_shake_stop(
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        try:
            await service.stop_shake()
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        service.clear_last_error_on_success()
        return CommandResponse(message="Shake cycle stopped")

    app.state.service = service
    return app


__all__ = ["create_app"]
